stages:
  - build

build-n-push:
  image: docker:19.03.4
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://localhost:2375"
  script:
    - docker build -t $FLEXSHOPPER_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA -f Dockerfile --no-cache .
    - docker tag $FLEXSHOPPER_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA $FLEXSHOPPER_REGISTRY/$CI_PROJECT_NAME:latest
    - docker push $FLEXSHOPPER_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker push $FLEXSHOPPER_REGISTRY/$CI_PROJECT_NAME:latest
  only:
    - master
